services:
  redis:
    image: redis:latest
    container_name: dropie-redis
    ports:
      - "6379:6379"
    # restart: unless-stopped  # 나중에 서버 배포 시 주석 해제 (컨테이너 자동 재시작)

  # 로컬에 MySQL이 이미 설치되어 있어 3306 포트 충돌 방지를 위해 3307로 매핑
  mysql:
    image: mysql:8.0
    container_name: dropie-mysql
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: dropie
    volumes:
      - mysql-data:/var/lib/mysql  # 컨테이너 재시작해도 데이터 유지

volumes:
  mysql-data:
